### ISSUE TITLE
可以正常启动，但是板载网卡不工作

### ISSUE THREAD

**Issue by LianYangCn** [GaryOAO/MSI-Z390i-hackintosh-OpenCore#3]
我的主板是 MSI MPG Z390I Game Edge AC，可以正常启动，但是板载网卡不工作，咋整

**Comment by GaryOAO** [comment]
我使用的是免驱卡，intel无线网卡请用网上方法解决。有线网卡应该已经正常驱动。

**Comment by LianYangCn** [comment]
我是双系统，win 10 可以正常驱动板载有线网卡，但是啥都不变，启动到 MacOS就显示网线没有插入，蓝牙不能用

**Comment by GaryOAO** [comment]
> 我是双系统，win 10 可以正常驱动板载有线网卡，但是啥都不变，启动到 MacOS就显示网线没有插入，蓝牙不能用

使用的是releases里的最新版吗

**Comment by LianYangCn** [comment]
> > 我是双系统，win 10 可以正常驱动板载有线网卡，但是啥都不变，启动到 MacOS就显示网线没有插入，蓝牙不能用
> 
> 使用的是releases里的最新版吗

1. 我用的是 releases 的最新版本
2. 我尝试用我之前Clover里面的 RealtekRTL8111.kext 替换 kexts里面的对应文件，居然就成功驱动网络了，而且蓝牙也好了

**Comment by LianYangCn** [comment]
另外 我也测试了一下 核显的 HDMI和DP端口都能正常驱动成功 双显示器 非常爽 之前我用 clover 的时候是不行的
非常感谢

**Comment by LianYangCn** [comment]
我多次确认使用你给的原版是没有办法驱动网络的
我使用的可以正常驱动网络的kext文件我也附在此供你参考

[RealtekRTL8111.kext.zip](https://github.com/GaryOAO/MSI-Z390i-hackintosh-OpenCore/files/6409580/RealtekRTL8111.kext.zip)

**Comment by LianYangCn** [comment]
我重新定制了一下USB口，蓝牙也可以正常使用了

**Comment by LianYangCn** [comment]
@GaryOAO 
我发现了另一个哭笑不得的问题
本来我想升级到 big sur，但是总是出错，一致找不到原因

后来无意中发现 config.plist 的 ACPI 设置中 存在 SSDT-EC.aml 但是 OC/ACPI 目录中并没有 SSDT-EC.aml 文件
所以实际上没有使用SSDT-EC.aml 从而导致不能正确升级
我使用的是 [OC-little/SSDT-EC](https://github.com/daliansky/OC-little/blob/master/03-%E4%BB%BF%E5%86%92%E8%AE%BE%E5%A4%87/02-1-%E4%BB%BF%E5%86%92EC/SSDT-EC.dsl)

我的EFI已经完美，谢谢作者 @GaryOAO
